<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <OutputType>Library</OutputType>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AssemblyName>SkillIssueToolkit.ActPlugin</AssemblyName>
    <RootNamespace>SkillIssueToolkit.ActPlugin</RootNamespace>
    <Version>1.0.0-beta.5</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="System.Net.Http" Version="4.3.4" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Advanced Combat Tracker">
      <HintPath>C:\Program Files (x86)\Advanced Combat Tracker\Advanced Combat Tracker.exe</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Include="Overlays\**" CopyToOutputDirectory="PreserveNewest" />
    <None Include="eq2overlay-class-abilities.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
